### ISSUE TITLE
Suggestion: add support for BCF files

### ISSUE THREAD

**Issue by fgvieira** [igvteam/igv-reports#55]
`create_report` only supports `vcf.gz` files, but would it be possible to also support `bcf`?
thanks,

**Comment by jrobinso** [comment]
@fgvieira This might actually work with very minor changes, but I don't have time to pursue it.   If you want to try, modify "getreader" in utils.py to return a vcf.VcrReader for file type vcf.    Since pysam understands bcf files it might just work (almost).   The other trick would be to create a igv.js track of type "vcf", since igv.js does not support bcf.  Again this might just work with no code changes other than a tweak to the format specifier for the output json, the format field in "get_track_json_dict" from tracks.py.   In this respect bcf is very similar to cram, which is actually output in the report as bam.
