### ISSUE TITLE
Embedded igv-report array length error

### ISSUE THREAD

**Issue by azbard** [igvteam/igv-reports#58]
Hi there - I'm embedding an igv-report in an iframe and it works fine except it pops up this error:
![invalid-aray-length-error](https://user-images.githubusercontent.com/83711448/147588674-28cd67f7-a73d-4c9e-8460-752f222e12d1.png)
Thoughts?

**Comment by jrobinso** [comment]
That's not a lot of information to go on.  If you can zip and share the report I will look at it.   Look in the console for errors.

**Comment by azbard** [comment]
Yes, sorry, that *was* vague. See attached. Open "array-error.html" and click on the "Pileups" tab
[array-error.zip](https://github.com/igvteam/igv-reports/files/7786071/array-error.zip)
.

**Comment by jrobinso** [comment]
I don't know but it must have something to do with the tab since the report
itself does not have any errors that I could find.    You might need to
insert a call to "browser.visibilityChanged()" somewhere,  see
https://github.com/igvteam/igv.js/wiki/Browser-API-2.0#visibilitychange and
also https://github.com/igvteam/igv.js/blob/master/dev/misc/tabs.html.
 That's just a guess.

**Comment by azbard** [comment]
Thanks for the quick response - will look into it and report back if I figure it out.  In the mean time, may as well close the issue.
