### ISSUE TITLE
converting the html to pdf

### ISSUE THREAD

**Issue by laxvid** [igvteam/igv-reports#80]
What is the best way to deliver pdf files of the snapshots rather than html ?  
The results are being viewed in an application that does not support html but does render pdf

**Comment by Kyomari** [comment]
There are several options available. There are many online converters available that allow you to upload HTML files and convert them to PDF format. Some popular options include PDFCrowd, PDFreactor, and HTML-to-PDF. Otherwise you could use libraries and APIs. There are also many libraries and APIs available that allow you to convert HTML to PDF programmatically. Some popular options include wkhtmltopdf, PrinceXML, and PhantomJS.

**Comment by jrobinso** [comment]
I'm not sure a html -> pdf converter is going to work,  because the rendering is done in javascript in a browser.   This project really isn't designed to render static images, the point of it is to render live, interactive pages.     It might be possible to write an a script with PhantomJS that would do the conversion, since that mimics a browser.

**Comment by jrobinso** [comment]
Closing as this doesn't appear to be technically possible.  I would love to be proven wrong via a pull request.
