### ISSUE TITLE
How to turn off downsampling option

### ISSUE THREAD

**Issue by canna1998** [igvteam/igv-reports#86]
By default, the Downsampling option is enabled in the generated html file.  I have checked the previous issues, it seems that there was no downsample function before, can I turn this option off and display all reads now？

**Comment by jrobinso** [comment]
You can do this, and many more things, by using the `--track-config` option to specify your tracks rather than just listing them by file path.    See the example using `--track-config` option in the README.    The track options are describe in the [igv.js wiki](https://github.com/igvteam/igv.js/wiki).  Specifically, for your case you would set `samplingDepth` in an alignment track config to a very large number, for example

Example of trackConfig.json
```
[
  {
    "name": "Variants",
    "url": "test/data/variants/variants.vcf.gz"
  },
  {
    "name": "Alignments",
    "url": "test/data/variants/recalibrated.bam",
    "samplingDepth": 1000000,
    "color": "rgb(0,150,150)"
  },
  {
    "name": "Genes",
    "type": "",
    "url": "test/data/hg38/refGene.txt.gz",
    "indexURL": "test/data/hg38/refGene.txt.gz.tbi"
  }
]
```
